version: '2'
services:
  app:
    build: php/.
    volumes:
     - ./www:/var/www
  proxy:
    build: nginx/.
    volumes_from:
      - app
    depends_on:
     - app
    ports:
     - "80:80"
     - "443:443"
